### ISSUE TITLE
[S1 - PBI1] Registrasi, Login, dan Logout

### ISSUE THREAD

**Issue by devfaus** [SI-RPL-2022/SI4303_B_IREPORT#1]
Saya sebagai admin/user ingin melakukan registrasi, login, dan logout sehingga saya dapat mengakses iReport

**Comment by zaidan-alaudin** [comment]
saya membuat use case scenario registrasi, login dan logout
![image](https://user-images.githubusercontent.com/101573075/160414643-f747b3ac-af2b-4cf3-af8f-98bb282a21d6.png)
