### ISSUE TITLE
[S1 - PBI6] Profile User Page

### ISSUE THREAD

**Issue by alaric2001** [SI-RPL-2022/SI4303_B_IREPORT#13]
Saya sebagai user ingin melihat about page sehingga saya mengetahui maksud dari web IREPORT

**Comment by MIrfan16** [comment]
Usecase scenario iReport: 
![Screenshot 2022-03-29 0813220](https://user-images.githubusercontent.com/92176063/160512804-497e1707-ea1b-409f-a534-3c2758ef9bb2.png)

**Comment by devfaus** [comment]
Usecase desciption:
Sistem akan menampilkan About Page berisi tentang deskripsi dari website iReport

Activity diagram:
![AAAAAAAAAAAAAActivity Diagram drawio](https://user-images.githubusercontent.com/83989420/160512511-4ae88323-5537-4c0d-9300-0311cfc388fc.png)

Mockup:
![Screenshot (2172)](https://user-images.githubusercontent.com/83989420/160512552-999f7c48-4fc8-4e9c-b1d7-caff25ae1912.png)
