### ISSUE TITLE
[S1 - PBI2] Form Input Laporan, serta Fitur Edit dan Delete Laporan

### ISSUE THREAD

**Issue by devfaus** [SI-RPL-2022/SI4303_B_IREPORT#2]
Saya sebagai user ingin melakukan form input laporan sehingga saya dapat memasukkan laporan yang ingin saya laporkan

Saya sebagai user ingin mengubah laporan yang saya sudah input sehingga laporan yang saya masukkan tidak salah

Saya sebagai user ingin fitur delete laporan sehingga saya dapat menghapus laporan yang telah saya buat, karena bisa saja saya melakukan kesalahan

**Comment by mhanafie** [comment]
Saya membuat Use Case Scenario : 
![Use Case](https://user-images.githubusercontent.com/87606173/160412506-73ea02f6-296d-4259-af50-4e00f81b0502.jpg)

**Comment by zaidan-alaudin** [comment]
Saya membuat Use Case Scenario delete laporan

![image](https://user-images.githubusercontent.com/101573075/160512043-eab3f70c-1ce5-403a-b30c-4f4c4671fe0b.png)
