### ISSUE TITLE
[S3 - PBI11] Update Profile

### ISSUE THREAD

**Issue by alaric2001** [SI-RPL-2022/SI4303_B_IREPORT#3]
Saya sebagai user ingin fitur update profile sehingga saya dapat mengubah dan mengoreksi profil saya

**Comment by Kamilianurunnadhifah** [comment]
![Fitur Profile](https://user-images.githubusercontent.com/92259786/172276349-33b07d00-55fb-4d36-aee3-de352a604cca.png)
![Fitur Reward](https://user-images.githubusercontent.com/92259786/172276443-5db7cc02-4f68-428c-ad28-fe49f6c79e15.png)

**Comment by Kamilianurunnadhifah** [comment]
activity diagram
![update profil](https://user-images.githubusercontent.com/92259786/172285752-f3cf28cb-1e2f-4e37-a311-544b0a4804c8.png)

**Comment by ekkynovrizalam** [comment]
termasuk edit photo

**Comment by MIrfan16** [comment]
https://user-images.githubusercontent.com/92176063/174843272-ad06e2ff-d610-4a36-a490-abd7172b4266.mp4

Demo fitur update profile
