### ISSUE TITLE
[S2 - PBI13] Fitur Filter Laporan

### ISSUE THREAD

**Issue by alaric2001** [SI-RPL-2022/SI4303_B_IREPORT#39]
Saya sebagai user ingin Fitur Filter Laporan agar saya dapat melihat Laporan berdasarkan trending dan wilayah laporannya

**Comment by mhanafie** [comment]
Saya membuat fitur Filter Laporan

![Filter Laporan](https://user-images.githubusercontent.com/87606173/165214817-30c3a853-e8a5-4641-87f2-6ac285a53310.jpg)

**Comment by mhanafie** [comment]
https://user-images.githubusercontent.com/87606173/170902755-fb4ba4f9-3ad2-4716-bbce-197e554829f0.mp4
