### ISSUE TITLE
[S1 - PBI3] Home Page

### ISSUE THREAD

**Issue by devfaus** [SI-RPL-2022/SI4303_B_IREPORT#4]
Saya sebagai user ingin membuat Home page sehingga saya dapat mencari/menjelajahi laporan-laporan yang telah dimasukkan oleh semua user

**Comment by devfaus** [comment]
Saya membuat Use Case Scenario :
![image](https://user-images.githubusercontent.com/83989420/160413685-d1659453-f8dc-466f-ab82-828fda3067a0.png)

**Comment by alaric2001** [comment]
Video demo tambahan fitur search

https://user-images.githubusercontent.com/76650101/163845705-c629adde-f6e8-4afb-b56f-93389499fe04.mp4
