### ISSUE TITLE
[S3 - PBI12] Info/Berita keadaan lokasi

### ISSUE THREAD

**Issue by devfaus** [SI-RPL-2022/SI4303_B_IREPORT#5]
Saya sebagai admin ingin membuat info/berita keadaan lokasi sehingga saya dapat memantau info/berita terkini pada keadaan lokasi yang telah dilaporkan

**Comment by Kamilianurunnadhifah** [comment]
diagram activity
![info berita](https://user-images.githubusercontent.com/92259786/172284706-fcd6adf0-c993-4a3d-8186-2260652f0081.png)

**Comment by Kamilianurunnadhifah** [comment]
![NEWS](https://user-images.githubusercontent.com/92259786/172284792-7bbd4f17-3f1c-4cf5-8df8-9bc428a51fec.png)

**Comment by ekkynovrizalam** [comment]
ini hanya di sisi user sehingga di tambahkan juga fitur search

**Comment by alaric2001** [comment]
https://user-images.githubusercontent.com/76650101/174915603-13d82646-3b37-463e-b80e-6ae45ca3189b.mp4
