### ISSUE TITLE
[S3 - PBI15] Comment Laporan

### ISSUE THREAD

**Issue by Kamilianurunnadhifah** [SI-RPL-2022/SI4303_B_IREPORT#52]
Saya sebagai user ingin memberikan komen di postingan laporan pada iReport

**Comment by mhanafie** [comment]
Activity Diagram
![Comment Laporan](https://user-images.githubusercontent.com/87606173/172285516-a008b7a2-8e14-4627-88e7-5556f6878f3a.jpg)

**Comment by ekkynovrizalam** [comment]
comment bisa di edit dan dihapus

**Comment by Kamilianurunnadhifah** [comment]
![View Detail Page Laporan](https://user-images.githubusercontent.com/92259786/172287567-51a956c0-dd5b-44aa-bce5-d0c7e613131c.png)

**Comment by mhanafie** [comment]
Video Demo 

https://user-images.githubusercontent.com/87606173/176087817-e878d33e-5bb0-46d1-aafe-71e148409120.mp4
