### ISSUE TITLE
[S3 - PBI16] Hapus Akun

### ISSUE THREAD

**Issue by Kamilianurunnadhifah** [SI-RPL-2022/SI4303_B_IREPORT#53]
Saya sebagai user bisa menghapus akun pada ireport

**Comment by mhanafie** [comment]
![Untitled](https://user-images.githubusercontent.com/87606173/172284823-208c4615-5959-4bfc-87d2-d7232570ee34.jpg)

**Comment by Kamilianurunnadhifah** [comment]
![Deleteteteet](https://user-images.githubusercontent.com/92259786/172286231-917e7712-a597-4eec-a913-ac13ccdb0586.png)

**Comment by ekkynovrizalam** [comment]
direvisi menjadi approve by admin

**Comment by Kamilianurunnadhifah** [comment]
https://user-images.githubusercontent.com/92259786/176106125-02d12865-184f-4532-9317-fe262f538136.mp4
