### ISSUE TITLE
[S3 - PBI17 ] Fitur Our Team

### ISSUE THREAD

**Issue by alaric2001** [SI-RPL-2022/SI4303_B_IREPORT#56]
Saya sebagai admin ingin fitur Our Team sehingga saya dapat menginput, melihat, mengupdate, dan menghapus tim yang mengembangkan web Ireport

**Comment by mhanafie** [comment]
Activity Diagram Our Team

Input Anggota Team
![Input Team](https://user-images.githubusercontent.com/87606173/173313614-1dc5f099-ee4d-4235-a296-2db85c19ec61.jpg)


Edit Anggota Team
![Edit Team](https://user-images.githubusercontent.com/87606173/173313669-0838e1dd-6689-4748-85c3-6e512e01ae20.jpg)

Delete Anggota Team
![Delete team](https://user-images.githubusercontent.com/87606173/173313729-ad46c686-e121-461d-aeae-e6b6daf4dd28.jpg)

**Comment by devfaus** [comment]
Mockup
![Screenshot (4062)](https://user-images.githubusercontent.com/83989420/173395079-9f019aa4-3ca4-46ab-95eb-40c8f0769c86.png)

**Comment by ekkynovrizalam** [comment]
konten harus dinamis ya. dapat di edit
